### ISSUE TITLE
Using the 3.0.0 Version in Swift

### ISSUE THREAD

**Issue by pleirosei** [davedelong/CHCSVParser#93]
Hello.  How exactly do I use the 3.0.0 version in swift?  Do I still need the CHCSVParser.m file?  The readme doesn't seem updated with this version.  Please assists, thanks.

**Comment by davedelong** [comment]
The 3.0.0 version of CHCSVParser has not been completed yet, which is why it has not been merged in to `master`. Use it at your own risk.
